spring:
  datasource:
    username: root
    password: jpfm1234
    url: jdbc:mysql://39.106.125.242:3306/jpfm_dev
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.alibaba.druid.proxy.DruidDriver
    #schema:
    #  - classpath:department.sql
    druid:
      initinitialSize: 20
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
