#日志级别
logging:
  level:
    root: debug

spring:
  #redis地址、端口、密码
  redis:
    host: localhost
    port: 6379
    password: 123456
    jedis:
      #连接池配置
      pool:
        max-active: 8
        max-wait: 10
        max-idle: 8
        min-idle: 1
    database: 0