#日志级别
logging:
  level:
    com:
      eppear: debug

spring:
  #redis地址、端口、密码
  redis:
    host: localhost
    port: 6379
    password: 123456
    jedis:
      #连接池配置
      pool:
        max-active: 8
        max-wait: 10
        max-idle: 8
        min-idle: 1
    database: 0
  security:
    user:
      password: 123
      name: admin
  #解决json乱码问题
  http:
    encoding:
      charset: utf-8
      force: true
  #数据库配置
  datasource:
    username: root
    password: jpfm1234
    url: jdbc:mysql://39.106.125.242:3306/baiju
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initinitialSize: 20
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  type-aliases-package: com.eppear.baiju.backstage.dao.model
  mapper-locations: classpath:mappers/**/*Mapper.xml
mapper:
  mappers: com.eppear.baiju.backstage.dao.config.MyMapper
  not-empty: true
  i-d-e-n-t-i-t-y: MSQL